### PR TITLE
22.7 fb usda pain categories

### PR DESCRIPTION
**Pull request by kollil**
Updated the USDA pain category code files.

### CODE REVIEW

**Comment by kollil** [comment]
@labkey-martyp , I am little confused. I added a new sql file to the existing PR, 22.7_fb_USDAPainCategories, but, Git behaved as if I was creating a new PR. 
Hope I didn't do anything wrong. Please correct me if I did anything wrong.

Thanks
Lakshmi

**Comment by kollil** [comment]
@labkey-martyp , I just realized that the previous changes were moved into prod without me doing "Squash and Merge". I wasn't ready to create the "default" branch for this PR until today. 

https://prime.ohsu.edu/ehr/ONPRC/EHR/dataEntryFormForQuery.view?schemaName=ehr_lookups&queryName=procedures&rowid=&query.sort=name&returnUrl=%2Fehr%2FONPRC%2FEHR%2FupdateQuery.view%3FschemaName%3Dehr_lookups%26query.queryName%3Dprocedures%26showImport%3Dtrue

The changes on this screen are incomplete. The field name is "USDA Pain Categories" and it's a drop down list not a Text box. I was working on the changes but it was installed into prod without my involvement. Please see the new updates I made today. These changes are final and I am preparing to create a default branch now.

I dont know how to fix this without disrupting the core files.
Please let me know the next steps.

Thanks
Lakshmi

**Comment by labkey-martyp** [comment]
@kollil Hi Lakshmi, here's the original PR for your reference on our discussion and when that was merged in. I'm not sure you have permission to merge in changes to the ehrModules repo. For these updates you don't need Procedure_Pain_Categories.sql, you just need to add the set to ehr.lookup_sets ([link to add it](https://prime.ohsu.edu/ldk/ONPRC/EHR/updateQuery.view?schemaName=ehr_lookups&query.queryName=lookup_sets)). Then it will look like a regular table in ehr_lookups (ehr_lookups.Procedure_Pain_Categories). You can then add your values to it or add them directly to ehr_lookups.lookups. Once that is done, the text box should convert to a dropdown option field. So please remove Procedure_Pain_Categories.sql from this PR and we can get it merged in.

**Comment by labkey-martyp** [comment]
> @kollil Hi Lakshmi, here's the original PR for your reference on our discussion and when that was merged in. I'm not sure you have permission to merge in changes to the ehrModules repo. For these updates you don't need Procedure_Pain_Categories.sql, you just need to add the set to ehr.lookup_sets ([link to add it](https://prime.ohsu.edu/ldk/ONPRC/EHR/updateQuery.view?schemaName=ehr_lookups&query.queryName=lookup_sets)). Then it will look like a regular table in ehr_lookups (ehr_lookups.Procedure_Pain_Categories). You can then add your values to it or add them directly to ehr_lookups.lookups. Once that is done, the text box should convert to a dropdown option field. So please remove Procedure_Pain_Categories.sql from this PR and we can get it merged in.

[Original PR](https://github.com/LabKey/ehrModules/pull/462)

**Comment by labkey-martyp** [comment]
@kollil Lakshmi, since this feature branch was already merged in once, I opened a new feature branch and PR with the column title change. I'm closing this PR to use that one instead. Please review that PR [here](https://github.com/LabKey/ehrModules/pull/483).

**Pull request closed without merging**
