### PR TITLE
Issue 44149 - increase cage.location column length

### PR DESCRIPTION
**Pull request by ankurjuneja**
#### Rationale
Cage trigger script concatenates room and cage in location column of size 24 and some centers have longer names for rooms and cages. This PR increases the length of location column to 100.

### CODE REVIEW

**Review by labkey-jeckels — CHANGES_REQUESTED** [review]
This change makes SQLServer angry. See the test failures. You'll need to drop the index and recreate after changing the column length.

Caused by: java.sql.SQLException: The index 'cage_location' is dependent on column 'location'.
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372) ~[jtds-1.3.1.jar:1.3.1]
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988) ~[jtds-1.3.1.jar:1.3.1]
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421) ~[jtds-1.3.1.jar:1.3.1]
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671) ~[jtds-1.3.1.jar:1.3.1]
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613) ~[jtds-1.3.1.jar:1.3.1]

**Review by labkey-jeckels — APPROVED** [review]
SQLServer tests got passed the module upgrade phase, so script revisions are working as desired

**Comment by ankurjuneja** [comment]
tests that failed are failing in release21.11-SNAPSHOT branch as well.

**Comment by ankurjuneja** [comment]
I will take a look at them.

**Pull request merged**
