### PR TITLE
Update procedures pain category title

### PR DESCRIPTION
**Pull request by labkey-martyp**
#### Rationale
Update title to USDA Pain Category

#### Related Pull Requests
* https://github.com/LabKey/ehrModules/pull/462

#### Changes
* Update title in schema and query.xml

### CODE REVIEW

**Review by kollil — APPROVED** [review]

**Comment by kollil** [comment]
Thanks Marty. I approved the PR.

You told me earlier also to create the pain categories in ehr_lookups. I did extacly what you told.
Added ehr_lookups.lookupsets = "Procedure_Pain_Category" and 
Added the reference values (B, C, D) in ehr_lookups.lookups .

I created a sql query "Procedure_Pain_Categories. sql" in study folder to retrieve the reference values and display them as a drop down list.  I was trying to mimic the code for  "procedure_drug_templates".
I used the sql in procedures.query.xml like this, please see the attached [procedure.query_xml.txt](https://github.com/LabKey/ehrModules/files/10316973/procedure.query_xml.txt).

**Comment by labkey-martyp** [comment]
Great thanks @kollil , I'll let it run the test then get that merged in.  

You shouldn't need an extra sql query to make the lookups work.  I added Procedure_Pain_Categories to primeuat for an example. Please check it out and you can add it to production in the same way to get that dropdown working.
- [ehr_lookups.lookup_sets](https://primeuat.ohsu.edu/ldk/ONPRC/EHR/updateQuery.view?schemaName=ehr_lookups&query.queryName=lookup_sets&query.setname~eq=Procedure_Pain_Categories)
- [ehr_lookups.Procedure_Pain_Categories](https://primeuat.ohsu.edu/ldk/ONPRC/EHR/updateQuery.view?schemaName=ehr_lookups&query.queryName=Procedure_Pain_Categories) (this is a virtual table created from ehr_lookups.lookups, but you can add rows directly to the Procedure_Pain_Categories table)
- [Add procedures UI with dropdown](https://primeuat.ohsu.edu/ehr/ONPRC/EHR/dataEntryFormForQuery.view?schemaName=ehr_lookups&queryName=procedures&rowid=&query.sort=name&returnUrl=%2Fehr%2FONPRC%2FEHR%2FupdateQuery.view%3FschemaName%3Dehr_lookups%26query.queryName%3Dprocedures%26showImport%3Dtrue)

**Comment by kollil** [comment]
Thanks Marty.

**Comment by kollil** [comment]
Thanks @labkey-martyp Marty, Looks like the changes are merged into the master branch. Could you please tell me when I can see the changes in prod?

**Pull request merged**
