### PR TITLE
Adjustments to blood summary plot

### PR DESCRIPTION
**Pull request by csebranek**
#### Rationale
Adding a legend for readability, and starting the y-axis at zero to more accurately show if an animal is almost out of blood.

#### Related Pull Requests
* 

#### Changes
*

### CODE REVIEW

**Review by labkey-martyp — COMMENTED** [review]
This looks great. As discussed, a couple changes for the y axis,
1. Handle the case where available blood goes below zero. Should just need to adjust the range and the plot will automatically shade that in red. Could consider extending y axis below zero if getting close to zero. Like subtracting 10% of max allowable from bottom is negative, then that is the y axis lower range, otherwise it's zero.
2. Maybe just adding 10% instead of 10mL to the top range of the y axis.

**Review by labkey-martyp — APPROVED** [review]
@csebranek This looks good. Please let me know when you're ready to merge this in. I have another PR that will need to be merged in as well.

**Comment by bbimber** [comment]
@csebranek and @labkey-martyp: out of curiosity, why does EHR need a separate server-side action to get the blood data? Why doesnt select rows with very minor client-side reformatting accomplish the same thing?

**Comment by labkey-martyp** [comment]
@bbimber Yeah I don't see anything that couldn't be done with select rows. I don't remember the reason we gave it it's own action. @csebranek something we can consider if there are further modifications here.

**Pull request merged**
