### PR TITLE
Added two new input screens and added one new tables.

### PR DESCRIPTION
**Pull request by Ohsudev**
#### Changes
EHR version of Compliance input screens.  Redesigned from previous versions of featue branch.

### CODE REVIEW

**Review by kollil — APPROVED** [review]
Is update on postgresql intentional?EHR_ComplianceDB/resources/schemas/dbscripts/postgresql/EHR_ComplianceDB-12.40-12.41.sql

**Comment by labkey-jeckels** [comment]
@kollil Yes, we need to make sure that the SQLServer and Postgres versions of the schema stay consistent. Thanks for putting in the Postgres side, Raymond. However, there are differences between the DBs (Postgres doesn't have NVARCHAR, for example) that will need to be fixed. I assume you don't have Postgres setup, @Ohsudev, so I can take a crack at this later today.

**Comment by labkey-jeckels** [comment]
@Ohsudev I pushed additional changes for Postgres compatibility (it uses SERIAL instead of IDENTITY and doesn't like GO statements). Let's make sure they're happy on TeamCity test runs but I hope that should be all that's needed.

**Review by labkey-jeckels — APPROVED** [review]

**Comment by Ohsudev** [comment]
No longer needed.

**Pull request closed without merging**
