### PR TITLE
avoid calls to ColumnInfo.getSelectName()

### PR DESCRIPTION
**Pull request by labkey-matthewb**
#### Rationale
fix usages of ColumnInfo.getSelectName()
usually getValueSql() or getFieldKey().toSQLString() is more correct.

### CODE REVIEW

**Review by labkey-jeckels — COMMENTED** [review]
These changes look good to me, but @labkey-ankurj can I ask you to double-check that they still work OK? Let me or Matt know if you need help with validation. The idea is that the results should be identical, but work in more scenarios (like custom queries, via more lookups, etc)

**Comment by labkey-ankurj** [comment]
getting this exception
`java.lang.AssertionError: Use getValueSql()
	at org.labkey.api.data.BaseColumnInfo.getSelectName(BaseColumnInfo.java:544)
	at org.labkey.ldk.query.DefaultTableCustomizer.appendEnddate(DefaultTableCustomizer.java:243)
	at org.labkey.ldk.query.DefaultTableCustomizer.appendCalculatedDateColumns(DefaultTableCustomizer.java:222)
	at org.labkey.ldk.LDKServiceImpl.appendCalculatedDateColumns(LDKServiceImpl.java:180)
	at org.labkey.ehr.table.DefaultEHRCustomizer.doSharedCustomization(DefaultEHRCustomizer.java:212)
	at org.labkey.ehr.table.DefaultEHRCustomizer.customizeDataset(DefaultEHRCustomizer.java:448)
	at org.labkey.ehr.table.DefaultEHRCustomizer.customize(DefaultEHRCustomizer.java:122)
	at org.labkey.api.data.AbstractTableInfo.configureViaTableCustomizer(AbstractTableInfo.java:1363)
	at org.labkey.api.data.AbstractTableInfo.loadFromXML(AbstractTableInfo.java:1126)
	at org.labkey.api.data.AbstractTableInfo.loadFromXML(AbstractTableInfo.java:1114)
	at org.labkey.api.query.FilteredTable.loadFromXML(FilteredTable.java:153)
	at org.labkey.api.data.AbstractTableInfo.overlayMetadata(AbstractTableInfo.java:1469)
	at org.labkey.study.query.DatasetTableImpl.overlayMetadataIfExists(DatasetTableImpl.java:967)
	at org.labkey.study.query.DatasetTableImpl.overlayMetadata(DatasetTableImpl.java:928)
	at org.labkey.api.query.UserSchema._getTableOrQuery(UserSchema.java:282)
	at org.labkey.api.query.UserSchema.getTable(UserSchema.java:191)
	at org.labkey.api.query.UserSchema.getTable(UserSchema.java:316)
	at org.labkey.query.controllers.GetSchemaQueryTreeAction.execute(GetSchemaQueryTreeAction.java:151)
	at org.labkey.query.controllers.GetSchemaQueryTreeAction.execute(GetSchemaQueryTreeAction.java:54)`

**Comment by labkey-matthewb** [comment]
There are four repositories with fb_getselectname branch.  Did you checkout LabDevKitModules?

* platform
* ehrModules
* LabDevKitModules
* onprcEHRModules

**Comment by labkey-ankurj** [comment]
> There are four repositories with fb_getselectname branch. Did you checkout LabDevKitModules?
> 
> * platform
> * ehrModules
> * LabDevKitModules
> * onprcEHRModules

just platforma and ehrModules, will checkout others now.

**Comment by labkey-ankurj** [comment]
tested, looks good.

**Review by labkey-ankurj — APPROVED** [review]

**Pull request merged**
