### PR TITLE
fix ehr data validation queries

### PR DESCRIPTION
**Pull request by ankurjuneja**
#### Rationale
This PR fixes the related PR for the centers that store dam and sire in different dataset than demographics

#### Related Pull Requests
* https://github.com/LabKey/ehrModules/pull/667

#### Changes
* use Id.parents.dam in place of dam from demographics

### CODE REVIEW

**Review by labkey-jeckels — COMMENTED** [review]
It might speed up the queries to use `study.demographicsParents` as the base query instead of starting with `study.demographics` and doing two separate lookup-based joins to it via `Id.parents`

**Comment by labkey-martyp** [comment]
> It might speed up the queries to use `study.demographicsParents` as the base query instead of starting with `study.demographics` and doing two separate lookup-based joins to it via `Id.parents`

@ankurjuneja How's the perf after your refactors Ankur. Want to investigate Josh's suggestion here?

**Comment by ankurjuneja** [comment]
@labkey-martyp After fixing the slowest one, all 4 queries are loading in ~40-50 seconds

**Review by labkey-martyp — APPROVED** [review]
Looks good. If you're seeing one or two of these queries taking the majority of the load time, probably worth looking into Josh's suggestion on that one.

**Pull request merged**
