### PR TITLE
Fix PG SQL error

### PR DESCRIPTION
**Pull request by bbimber**
This is related to https://github.com/LabKey/ehrModules/pull/485. I'm writing this to target 22.11 since that's where it hit us (TeamCity's build is failing); however, maybe you want 22.7 and then to merge it forward?

### CODE REVIEW

**Comment by bbimber** [comment]
BTW - shouldnt TeamCity have caught this? does it not build EHR modules in the default tests?

**Review by labkey-martyp — COMMENTED** [review]
Shoot, thanks for catching this. I just ran into it on another server as well. I'll get a PR open for 22.7. Sorry if that messed up an upgrade for you.

**Comment by labkey-martyp** [comment]
Closing this PR. Using this 22.7 PR instead. https://github.com/LabKey/ehrModules/pull/491

**Comment by labkey-tchad** [comment]
Going to merge this separately across release branches to fix them all in parallel instead of rolling the fix forward over a few days as our normal merge process would do.

**Review by labkey-martyp — APPROVED** [review]

**Pull request merged**
