### PR TITLE
Add nonces to 70 EHR pages

### PR DESCRIPTION
**Pull request by labkey-adam**
#### Rationale
First pass search & replace

### CODE REVIEW

**Comment by bbimber** [comment]
@labkey-adam: do you have some semi-automated way to find/add these, or is it fairly manual?

**Comment by labkey-adam** [comment]
> @labkey-adam: do you have some semi-automated way to find/add these, or is it fairly manual?

These are easy... just a regular expression search & replace in IntelliJ: `<script((?!nonce)(?!src)(?!path).)*>`

This is just a first step... I expect there are real inline JavaScript issues that can be trickier to resolve. BTW: TeamCity is now running all test suites with a Content Security Policy that reports inline script and missing nonces, but doesn't block. Report shows up in the artifacts along with all the other logs.

**Comment by bbimber** [comment]
> > @labkey-adam: do you have some semi-automated way to find/add these, or is it fairly manual?
> 
> These are easy... just a regular expression search & replace in IntelliJ: `<script((?!nonce)(?!src)(?!path).)*>`
> 
> This is just a first step... I expect there are real inline JavaScript issues that can be trickier to resolve. BTW: TeamCity is now running all test suites with a Content Security Policy that reports inline script and missing nonces, but doesn't block. Report shows up in the artifacts along with all the other logs.

OK. Is there a timeline when you are hoping to resolve this kind of stuff and tighten security?

**Review by labkey-matthewb — APPROVED** [review]

**Comment by labkey-adam** [comment]
> > > @labkey-adam: do you have some semi-automated way to find/add these, or is it fairly manual?
> > 
> > 
> > These are easy... just a regular expression search & replace in IntelliJ: `<script((?!nonce)(?!src)(?!path).)*>`
> > This is just a first step... I expect there are real inline JavaScript issues that can be trickier to resolve. BTW: TeamCity is now running all test suites with a Content Security Policy that reports inline script and missing nonces, but doesn't block. Report shows up in the artifacts along with all the other logs.
> 
> OK. Is there a timeline when you are hoping to resolve this kind of stuff and tighten security?

Following up via email...

**Pull request merged**
