### PR TITLE
Attempt to fix test timing (#224)

### PR DESCRIPTION
**Pull request by bbimber**
Let's just make it easier to do develop

### CODE REVIEW

**Comment by labkey-jeckels** [comment]
Note that TeamCity and GitHub can get confused when you have the same feature branch suffix across different release prefixes. There's a build in the queue to see if the test is happier here:

https://teamcity.labkey.org/buildConfiguration/LabkeyTrunk_EhrSqlserver/1521990

I'm separately working on the slew of EHR failures on the QC state not being found in the triggers

**Comment by labkey-jeckels** [comment]
This branch was out of date with develop, which caused the build to fail due to missing refactors. I've merged in the latest to this FB and we'll see what the tests look like on the next run.

**Review by labkey-jeckels — APPROVED** [review]
The viral load passed so cleared to merge

**Comment by bbimber** [comment]
thank you. let's hope i can do this more smoothly in the future

**Pull request merged**
